apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-auth-sidecar-prod

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

# Production-specific patches
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: my-application

  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "96Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
    target:
      kind: Deployment
      name: my-application

configMapGenerator:
  - name: k8s-auth-sidecar-config
    behavior: merge
    literals:
      - QUARKUS_LOG_LEVEL=WARN
      - SIDECAR_LOG_LEVEL=INFO
      - QUARKUS_LOG_JSON=true
      - OTEL_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - SIDECAR_OPA_EMBEDDED_POOL_ACQUIRE_TIMEOUT_MS=50

images:
  - name: de.edeka.eit/k8s-auth-sidecar
    newTag: "0.3.1"
